In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

tf.random.set_seed(777)

2.3.1


In [2]:
# 8개의 데이터, 4개의 feature
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
# 8개의 feature
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
print(x_data)
# convert int numpy and float format
x_data = np.asarray(x_data, dtype = np.float32)
y_data = np.asarray(y_data, dtype = np.float32)

[[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]


In [3]:
#@@@@@@@@@화긴~~~~~@@@@@@@@@@@@
x_data
# 결과를 보면 1. 해서 float형으로 바뀐 것을볼 수 있다.

array([[1., 2., 1., 1.],
       [2., 1., 3., 2.],
       [3., 1., 3., 4.],
       [4., 1., 5., 5.],
       [1., 7., 5., 5.],
       [1., 2., 5., 6.],
       [1., 6., 6., 6.],
       [1., 7., 7., 7.]], dtype=float32)

In [4]:
# dataset을 선언합니다.
nb_classes = 3 #class의 개수
# 

print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 3)


In [5]:
# Weight, bias를 setting하는 것
W = tf.Variable(tf.random.normal((4, nb_classes)), name = 'weight')
    # 4개의 특징과 3개의 클래스를 정의
    # random.normal 값으로 랜덤값을 정해줌
b = tf.Variable(tf.random.normal((nb_classes,)), name = 'bias')
variables =[W,b]
    # variable으로 저장함
    
# Weight, bias값을 출력해본다.
print(W)
print(b)

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.7706481 ,  0.37335402, -0.05576323],
       [ 0.00358377, -0.5898363 ,  1.5702795 ],
       [ 0.2460895 , -0.09918973,  1.4418385 ],
       [ 0.3200988 ,  0.526784  , -0.7703731 ]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([-1.3080608 , -0.13253094,  0.5513761 ], dtype=float32)>


In [6]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[1.36571955e-02 7.90162385e-03 9.78441238e-01]
 [3.92597765e-02 1.70347411e-02 9.43705440e-01]
 [3.80385250e-01 1.67723164e-01 4.51891571e-01]
 [3.23390484e-01 5.90759404e-02 6.17533624e-01]
 [3.62997412e-06 6.20727292e-08 9.99996305e-01]
 [2.62520202e-02 1.07279615e-02 9.63019967e-01]
 [1.56525111e-05 4.21802781e-07 9.99983907e-01]
 [2.94076904e-06 3.81133276e-08 9.99997020e-01]], shape=(8, 3), dtype=float32)


In [7]:
# softmax값 확인해보기
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype = np.float32)

print(hypothesis(sample_db))
# 결과를 보면 첫번째 값이 가장 큰 것을 확인할 수 있음.
# 결과값 세개 모두 더하면 1이 나옴. [4개]가 들어가면 a,b,c중 하나 고르는거 softmax 함수로

tf.Tensor([[0.9302204  0.06200533 0.00777428]], shape=(1, 3), dtype=float32)


In [8]:
#cost 구하는 함수
def cost_fn(X, Y):
    logits = hypothesis(X)
        # softmax 함수를 적용한 다음
    cost = -tf.reduce_sum(Y *tf.math.log(logits), axis = -1)
        # cross entropy값을 이용해 구함 (Y*log(y_hat))
    cost_mean = tf.reduce_mean(cost)
        # 그 다음 cost의 평균을 구함
    return cost_mean

print(cost_fn(x_data, y_data))
# cost의 최종 평균이 출력됨

tf.Tensor(6.07932, shape=(), dtype=float32)


In [9]:
# 이건 y=x^2 가 있을 때 y에 대해서 x를 미분했을때, 3일때 y값을 구하는거
x =  tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = x*x  # x^2
dy_dx = g.gradient(y,x)
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [33]:
# cost함수를 최적화 하기 위해 경사하강법을 사용함
# 경사하강법 (Gradient Function)을 구현해보자.

def counter():
    i = 0
    def count():
        nonlocal i
        i += 1
        return i
    return count

c = counter()
# 참고로 with - as 함수는 문해프 마지막단원 파일처리할 때 많이 배웠었음
# GradientTape()는 context안에서 실행되는 모든 연산을 테이프에 '기록'함
# 그 다음 텐서플러오눈 후진 방식 자동 미분을 사용해 테이프에 기록된 연산의 그래디언트를 계산함.
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        
        print("loss" ,c())
        print(loss)
        grads = tape.gradient(loss, variables)
            # variables = [W, b]
        print("grads")
        return grads
    
print(grad_fn(x_data, y_data))

loss 1
tf.Tensor(0.09595555, shape=(), dtype=float32)
grads
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.00492847,  0.00100384, -0.00593227],
       [ 0.00166355,  0.00089782, -0.00256141],
       [-0.00456257,  0.00075494,  0.00380766],
       [ 0.00132797, -0.00238956,  0.00106162]], dtype=float32)>, None]


In [34]:
def fit(X, Y, epochs = 2000, verbose = 100):  #2000번 반복
    optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
        # 경사하강법을 사용하세요
    
    for i in range(epochs):
        grads = grad_fn(X, Y)
        if ((i==0) | ((i + 1)%verbose == 0)):
            print(W)
            print("미분값: ")
            print(grads)
        optimizer.apply_gradients(zip(grads, variables))
        if ((i==0) | ((i + 1)%verbose == 0)):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
        
fit(x_data, y_data)

loss 2
tf.Tensor(0.09595555, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-6.252283  ,  0.19977517,  7.140748  ],
       [-1.2583793 , -0.40887877,  2.6512926 ],
       [ 6.135336  , -0.8454327 , -3.701212  ],
       [-2.0049138 ,  2.8055422 , -0.724117  ]], dtype=float32)>
미분값: 
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.00492847,  0.00100384, -0.00593227],
       [ 0.00166355,  0.00089782, -0.00256141],
       [-0.00456257,  0.00075494,  0.00380766],
       [ 0.00132797, -0.00238956,  0.00106162]], dtype=float32)>, None]
Loss at epoch 1: 0.095944
loss 3
tf.Tensor(0.09594412, shape=(), dtype=float32)
grads
loss 4
tf.Tensor(0.09593262, shape=(), dtype=float32)
grads
loss 5
tf.Tensor(0.09592111, shape=(), dtype=float32)
grads
loss 6
tf.Tensor(0.095909566, shape=(), dtype=float32)
grads
loss 7
tf.Tensor(0.095897995, shape=(), dtype=float32)
grads
loss 8
tf.Tensor(0.09588661, shape=(), dtype=float32)
grads
loss 9
tf.Ten

loss 52
tf.Tensor(0.0953834, shape=(), dtype=float32)
grads
loss 53
tf.Tensor(0.095371954, shape=(), dtype=float32)
grads
loss 54
tf.Tensor(0.09536064, shape=(), dtype=float32)
grads
loss 55
tf.Tensor(0.09534927, shape=(), dtype=float32)
grads
loss 56
tf.Tensor(0.095337905, shape=(), dtype=float32)
grads
loss 57
tf.Tensor(0.09532654, shape=(), dtype=float32)
grads
loss 58
tf.Tensor(0.09531511, shape=(), dtype=float32)
grads
loss 59
tf.Tensor(0.09530382, shape=(), dtype=float32)
grads
loss 60
tf.Tensor(0.0952924, shape=(), dtype=float32)
grads
loss 61
tf.Tensor(0.095281035, shape=(), dtype=float32)
grads
loss 62
tf.Tensor(0.09526976, shape=(), dtype=float32)
grads
loss 63
tf.Tensor(0.09525836, shape=(), dtype=float32)
grads
loss 64
tf.Tensor(0.095247045, shape=(), dtype=float32)
grads
loss 65
tf.Tensor(0.09523561, shape=(), dtype=float32)
grads
loss 66
tf.Tensor(0.095224306, shape=(), dtype=float32)
grads
loss 67
tf.Tensor(0.09521301, shape=(), dtype=float32)
grads
loss 68
tf.Tensor(0.0

Loss at epoch 100: 0.094818
loss 102
tf.Tensor(0.09481774, shape=(), dtype=float32)
grads
loss 103
tf.Tensor(0.09480646, shape=(), dtype=float32)
grads
loss 104
tf.Tensor(0.094795235, shape=(), dtype=float32)
grads
loss 105
tf.Tensor(0.09478399, shape=(), dtype=float32)
grads
loss 106
tf.Tensor(0.0947728, shape=(), dtype=float32)
grads
loss 107
tf.Tensor(0.09476146, shape=(), dtype=float32)
grads
loss 108
tf.Tensor(0.09475018, shape=(), dtype=float32)
grads
loss 109
tf.Tensor(0.094739065, shape=(), dtype=float32)
grads
loss 110
tf.Tensor(0.09472781, shape=(), dtype=float32)
grads
loss 111
tf.Tensor(0.09471661, shape=(), dtype=float32)
grads
loss 112
tf.Tensor(0.09470538, shape=(), dtype=float32)
grads
loss 113
tf.Tensor(0.09469412, shape=(), dtype=float32)
grads
loss 114
tf.Tensor(0.09468295, shape=(), dtype=float32)
grads
loss 115
tf.Tensor(0.09467177, shape=(), dtype=float32)
grads
loss 116
tf.Tensor(0.09466052, shape=(), dtype=float32)
grads
loss 117
tf.Tensor(0.09464927, shape=(), 

loss 155
tf.Tensor(0.09422515, shape=(), dtype=float32)
grads
loss 156
tf.Tensor(0.094214074, shape=(), dtype=float32)
grads
loss 157
tf.Tensor(0.09420298, shape=(), dtype=float32)
grads
loss 158
tf.Tensor(0.094191864, shape=(), dtype=float32)
grads
loss 159
tf.Tensor(0.09418077, shape=(), dtype=float32)
grads
loss 160
tf.Tensor(0.09416965, shape=(), dtype=float32)
grads
loss 161
tf.Tensor(0.09415853, shape=(), dtype=float32)
grads
loss 162
tf.Tensor(0.094147444, shape=(), dtype=float32)
grads
loss 163
tf.Tensor(0.094136275, shape=(), dtype=float32)
grads
loss 164
tf.Tensor(0.09412533, shape=(), dtype=float32)
grads
loss 165
tf.Tensor(0.09411414, shape=(), dtype=float32)
grads
loss 166
tf.Tensor(0.09410313, shape=(), dtype=float32)
grads
loss 167
tf.Tensor(0.09409201, shape=(), dtype=float32)
grads
loss 168
tf.Tensor(0.094080925, shape=(), dtype=float32)
grads
loss 169
tf.Tensor(0.09406994, shape=(), dtype=float32)
grads
loss 170
tf.Tensor(0.09405881, shape=(), dtype=float32)
grads
los

loss 205
tf.Tensor(0.09367273, shape=(), dtype=float32)
grads
loss 206
tf.Tensor(0.093661815, shape=(), dtype=float32)
grads
loss 207
tf.Tensor(0.093650766, shape=(), dtype=float32)
grads
loss 208
tf.Tensor(0.09363982, shape=(), dtype=float32)
grads
loss 209
tf.Tensor(0.093628824, shape=(), dtype=float32)
grads
loss 210
tf.Tensor(0.09361789, shape=(), dtype=float32)
grads
loss 211
tf.Tensor(0.093606874, shape=(), dtype=float32)
grads
loss 212
tf.Tensor(0.09359591, shape=(), dtype=float32)
grads
loss 213
tf.Tensor(0.09358494, shape=(), dtype=float32)
grads
loss 214
tf.Tensor(0.093574025, shape=(), dtype=float32)
grads
loss 215
tf.Tensor(0.09356308, shape=(), dtype=float32)
grads
loss 216
tf.Tensor(0.0935521, shape=(), dtype=float32)
grads
loss 217
tf.Tensor(0.09354104, shape=(), dtype=float32)
grads
loss 218
tf.Tensor(0.09353011, shape=(), dtype=float32)
grads
loss 219
tf.Tensor(0.093519256, shape=(), dtype=float32)
grads
loss 220
tf.Tensor(0.09350826, shape=(), dtype=float32)
grads
los

loss 258
tf.Tensor(0.09309399, shape=(), dtype=float32)
grads
loss 259
tf.Tensor(0.093083136, shape=(), dtype=float32)
grads
loss 260
tf.Tensor(0.09307222, shape=(), dtype=float32)
grads
loss 261
tf.Tensor(0.09306142, shape=(), dtype=float32)
grads
loss 262
tf.Tensor(0.093050584, shape=(), dtype=float32)
grads
loss 263
tf.Tensor(0.09303975, shape=(), dtype=float32)
grads
loss 264
tf.Tensor(0.093028955, shape=(), dtype=float32)
grads
loss 265
tf.Tensor(0.093018055, shape=(), dtype=float32)
grads
loss 266
tf.Tensor(0.09300725, shape=(), dtype=float32)
grads
loss 267
tf.Tensor(0.09299647, shape=(), dtype=float32)
grads
loss 268
tf.Tensor(0.09298554, shape=(), dtype=float32)
grads
loss 269
tf.Tensor(0.09297474, shape=(), dtype=float32)
grads
loss 270
tf.Tensor(0.092963904, shape=(), dtype=float32)
grads
loss 271
tf.Tensor(0.09295307, shape=(), dtype=float32)
grads
loss 272
tf.Tensor(0.09294227, shape=(), dtype=float32)
grads
loss 273
tf.Tensor(0.09293144, shape=(), dtype=float32)
grads
los

loss 308
tf.Tensor(0.09255437, shape=(), dtype=float32)
grads
loss 309
tf.Tensor(0.09254363, shape=(), dtype=float32)
grads
loss 310
tf.Tensor(0.092532896, shape=(), dtype=float32)
grads
loss 311
tf.Tensor(0.092522144, shape=(), dtype=float32)
grads
loss 312
tf.Tensor(0.092511415, shape=(), dtype=float32)
grads
loss 313
tf.Tensor(0.09250072, shape=(), dtype=float32)
grads
loss 314
tf.Tensor(0.09248998, shape=(), dtype=float32)
grads
loss 315
tf.Tensor(0.09247923, shape=(), dtype=float32)
grads
loss 316
tf.Tensor(0.092468485, shape=(), dtype=float32)
grads
loss 317
tf.Tensor(0.09245786, shape=(), dtype=float32)
grads
loss 318
tf.Tensor(0.092447184, shape=(), dtype=float32)
grads
loss 319
tf.Tensor(0.09243638, shape=(), dtype=float32)
grads
loss 320
tf.Tensor(0.092425734, shape=(), dtype=float32)
grads
loss 321
tf.Tensor(0.092415005, shape=(), dtype=float32)
grads
loss 322
tf.Tensor(0.0924043, shape=(), dtype=float32)
grads
loss 323
tf.Tensor(0.09239358, shape=(), dtype=float32)
grads
lo

loss 361
tf.Tensor(0.09198889, shape=(), dtype=float32)
grads
loss 362
tf.Tensor(0.09197828, shape=(), dtype=float32)
grads
loss 363
tf.Tensor(0.09196767, shape=(), dtype=float32)
grads
loss 364
tf.Tensor(0.091957, shape=(), dtype=float32)
grads
loss 365
tf.Tensor(0.09194649, shape=(), dtype=float32)
grads
loss 366
tf.Tensor(0.09193584, shape=(), dtype=float32)
grads
loss 367
tf.Tensor(0.09192526, shape=(), dtype=float32)
grads
loss 368
tf.Tensor(0.091914706, shape=(), dtype=float32)
grads
loss 369
tf.Tensor(0.091904104, shape=(), dtype=float32)
grads
loss 370
tf.Tensor(0.0918935, shape=(), dtype=float32)
grads
loss 371
tf.Tensor(0.091882944, shape=(), dtype=float32)
grads
loss 372
tf.Tensor(0.091872394, shape=(), dtype=float32)
grads
loss 373
tf.Tensor(0.091861755, shape=(), dtype=float32)
grads
loss 374
tf.Tensor(0.0918512, shape=(), dtype=float32)
grads
loss 375
tf.Tensor(0.09184063, shape=(), dtype=float32)
grads
loss 376
tf.Tensor(0.09183011, shape=(), dtype=float32)
grads
loss 37

loss 411
tf.Tensor(0.09146157, shape=(), dtype=float32)
grads
loss 412
tf.Tensor(0.091451034, shape=(), dtype=float32)
grads
loss 413
tf.Tensor(0.091440596, shape=(), dtype=float32)
grads
loss 414
tf.Tensor(0.09143011, shape=(), dtype=float32)
grads
loss 415
tf.Tensor(0.091419525, shape=(), dtype=float32)
grads
loss 416
tf.Tensor(0.09140917, shape=(), dtype=float32)
grads
loss 417
tf.Tensor(0.09139866, shape=(), dtype=float32)
grads
loss 418
tf.Tensor(0.09138818, shape=(), dtype=float32)
grads
loss 419
tf.Tensor(0.091377616, shape=(), dtype=float32)
grads
loss 420
tf.Tensor(0.09136723, shape=(), dtype=float32)
grads
loss 421
tf.Tensor(0.09135684, shape=(), dtype=float32)
grads
loss 422
tf.Tensor(0.09134636, shape=(), dtype=float32)
grads
loss 423
tf.Tensor(0.09133577, shape=(), dtype=float32)
grads
loss 424
tf.Tensor(0.09132535, shape=(), dtype=float32)
grads
loss 425
tf.Tensor(0.09131497, shape=(), dtype=float32)
grads
loss 426
tf.Tensor(0.091304496, shape=(), dtype=float32)
grads
los

loss 464
tf.Tensor(0.0909089, shape=(), dtype=float32)
grads
loss 465
tf.Tensor(0.09089853, shape=(), dtype=float32)
grads
loss 466
tf.Tensor(0.09088815, shape=(), dtype=float32)
grads
loss 467
tf.Tensor(0.09087786, shape=(), dtype=float32)
grads
loss 468
tf.Tensor(0.0908675, shape=(), dtype=float32)
grads
loss 469
tf.Tensor(0.090857044, shape=(), dtype=float32)
grads
loss 470
tf.Tensor(0.09084681, shape=(), dtype=float32)
grads
loss 471
tf.Tensor(0.09083642, shape=(), dtype=float32)
grads
loss 472
tf.Tensor(0.090826094, shape=(), dtype=float32)
grads
loss 473
tf.Tensor(0.09081571, shape=(), dtype=float32)
grads
loss 474
tf.Tensor(0.09080529, shape=(), dtype=float32)
grads
loss 475
tf.Tensor(0.090795055, shape=(), dtype=float32)
grads
loss 476
tf.Tensor(0.090784654, shape=(), dtype=float32)
grads
loss 477
tf.Tensor(0.09077436, shape=(), dtype=float32)
grads
loss 478
tf.Tensor(0.09076397, shape=(), dtype=float32)
grads
loss 479
tf.Tensor(0.09075365, shape=(), dtype=float32)
grads
loss 4

grads
loss 514
tf.Tensor(0.09039341, shape=(), dtype=float32)
grads
loss 515
tf.Tensor(0.09038323, shape=(), dtype=float32)
grads
loss 516
tf.Tensor(0.09037301, shape=(), dtype=float32)
grads
loss 517
tf.Tensor(0.09036276, shape=(), dtype=float32)
grads
loss 518
tf.Tensor(0.09035247, shape=(), dtype=float32)
grads
loss 519
tf.Tensor(0.09034221, shape=(), dtype=float32)
grads
loss 520
tf.Tensor(0.090332, shape=(), dtype=float32)
grads
loss 521
tf.Tensor(0.090321735, shape=(), dtype=float32)
grads
loss 522
tf.Tensor(0.090311565, shape=(), dtype=float32)
grads
loss 523
tf.Tensor(0.09030128, shape=(), dtype=float32)
grads
loss 524
tf.Tensor(0.09029098, shape=(), dtype=float32)
grads
loss 525
tf.Tensor(0.09028081, shape=(), dtype=float32)
grads
loss 526
tf.Tensor(0.09027056, shape=(), dtype=float32)
grads
loss 527
tf.Tensor(0.0902604, shape=(), dtype=float32)
grads
loss 528
tf.Tensor(0.09025014, shape=(), dtype=float32)
grads
loss 529
tf.Tensor(0.090239935, shape=(), dtype=float32)
grads
lo

loss 567
tf.Tensor(0.089853235, shape=(), dtype=float32)
grads
loss 568
tf.Tensor(0.089843094, shape=(), dtype=float32)
grads
loss 569
tf.Tensor(0.08983298, shape=(), dtype=float32)
grads
loss 570
tf.Tensor(0.08982282, shape=(), dtype=float32)
grads
loss 571
tf.Tensor(0.089812726, shape=(), dtype=float32)
grads
loss 572
tf.Tensor(0.08980261, shape=(), dtype=float32)
grads
loss 573
tf.Tensor(0.089792445, shape=(), dtype=float32)
grads
loss 574
tf.Tensor(0.08978239, shape=(), dtype=float32)
grads
loss 575
tf.Tensor(0.08977225, shape=(), dtype=float32)
grads
loss 576
tf.Tensor(0.08976215, shape=(), dtype=float32)
grads
loss 577
tf.Tensor(0.089752115, shape=(), dtype=float32)
grads
loss 578
tf.Tensor(0.0897419, shape=(), dtype=float32)
grads
loss 579
tf.Tensor(0.08973177, shape=(), dtype=float32)
grads
loss 580
tf.Tensor(0.089721754, shape=(), dtype=float32)
grads
loss 581
tf.Tensor(0.089711525, shape=(), dtype=float32)
grads
loss 582
tf.Tensor(0.0897015, shape=(), dtype=float32)
grads
los

loss 617
tf.Tensor(0.08934926, shape=(), dtype=float32)
grads
loss 618
tf.Tensor(0.089339286, shape=(), dtype=float32)
grads
loss 619
tf.Tensor(0.0893293, shape=(), dtype=float32)
grads
loss 620
tf.Tensor(0.08931928, shape=(), dtype=float32)
grads
loss 621
tf.Tensor(0.08930933, shape=(), dtype=float32)
grads
loss 622
tf.Tensor(0.08929923, shape=(), dtype=float32)
grads
loss 623
tf.Tensor(0.08928922, shape=(), dtype=float32)
grads
loss 624
tf.Tensor(0.089279264, shape=(), dtype=float32)
grads
loss 625
tf.Tensor(0.08926919, shape=(), dtype=float32)
grads
loss 626
tf.Tensor(0.08925915, shape=(), dtype=float32)
grads
loss 627
tf.Tensor(0.089249186, shape=(), dtype=float32)
grads
loss 628
tf.Tensor(0.08923911, shape=(), dtype=float32)
grads
loss 629
tf.Tensor(0.08922918, shape=(), dtype=float32)
grads
loss 630
tf.Tensor(0.08921923, shape=(), dtype=float32)
grads
loss 631
tf.Tensor(0.08920919, shape=(), dtype=float32)
grads
loss 632
tf.Tensor(0.08919923, shape=(), dtype=float32)
grads
loss 6

loss 670
tf.Tensor(0.088821, shape=(), dtype=float32)
grads
loss 671
tf.Tensor(0.08881117, shape=(), dtype=float32)
grads
loss 672
tf.Tensor(0.08880125, shape=(), dtype=float32)
grads
loss 673
tf.Tensor(0.08879149, shape=(), dtype=float32)
grads
loss 674
tf.Tensor(0.08878149, shape=(), dtype=float32)
grads
loss 675
tf.Tensor(0.088771604, shape=(), dtype=float32)
grads
loss 676
tf.Tensor(0.08876172, shape=(), dtype=float32)
grads
loss 677
tf.Tensor(0.08875184, shape=(), dtype=float32)
grads
loss 678
tf.Tensor(0.0887419, shape=(), dtype=float32)
grads
loss 679
tf.Tensor(0.088732064, shape=(), dtype=float32)
grads
loss 680
tf.Tensor(0.08872211, shape=(), dtype=float32)
grads
loss 681
tf.Tensor(0.08871224, shape=(), dtype=float32)
grads
loss 682
tf.Tensor(0.08870228, shape=(), dtype=float32)
grads
loss 683
tf.Tensor(0.0886925, shape=(), dtype=float32)
grads
loss 684
tf.Tensor(0.088682555, shape=(), dtype=float32)
grads
loss 685
tf.Tensor(0.08867271, shape=(), dtype=float32)
grads
loss 686


loss 720
tf.Tensor(0.0883283, shape=(), dtype=float32)
grads
loss 721
tf.Tensor(0.08831847, shape=(), dtype=float32)
grads
loss 722
tf.Tensor(0.08830874, shape=(), dtype=float32)
grads
loss 723
tf.Tensor(0.08829889, shape=(), dtype=float32)
grads
loss 724
tf.Tensor(0.08828913, shape=(), dtype=float32)
grads
loss 725
tf.Tensor(0.08827922, shape=(), dtype=float32)
grads
loss 726
tf.Tensor(0.08826952, shape=(), dtype=float32)
grads
loss 727
tf.Tensor(0.08825968, shape=(), dtype=float32)
grads
loss 728
tf.Tensor(0.08824999, shape=(), dtype=float32)
grads
loss 729
tf.Tensor(0.08824007, shape=(), dtype=float32)
grads
loss 730
tf.Tensor(0.08823037, shape=(), dtype=float32)
grads
loss 731
tf.Tensor(0.08822057, shape=(), dtype=float32)
grads
loss 732
tf.Tensor(0.088210836, shape=(), dtype=float32)
grads
loss 733
tf.Tensor(0.08820104, shape=(), dtype=float32)
grads
loss 734
tf.Tensor(0.08819129, shape=(), dtype=float32)
grads
loss 735
tf.Tensor(0.08818141, shape=(), dtype=float32)
grads
loss 736

loss 773
tf.Tensor(0.08781165, shape=(), dtype=float32)
grads
loss 774
tf.Tensor(0.08780198, shape=(), dtype=float32)
grads
loss 775
tf.Tensor(0.08779229, shape=(), dtype=float32)
grads
loss 776
tf.Tensor(0.08778259, shape=(), dtype=float32)
grads
loss 777
tf.Tensor(0.087772846, shape=(), dtype=float32)
grads
loss 778
tf.Tensor(0.08776325, shape=(), dtype=float32)
grads
loss 779
tf.Tensor(0.087753564, shape=(), dtype=float32)
grads
loss 780
tf.Tensor(0.08774386, shape=(), dtype=float32)
grads
loss 781
tf.Tensor(0.087734245, shape=(), dtype=float32)
grads
loss 782
tf.Tensor(0.08772452, shape=(), dtype=float32)
grads
loss 783
tf.Tensor(0.08771488, shape=(), dtype=float32)
grads
loss 784
tf.Tensor(0.087705195, shape=(), dtype=float32)
grads
loss 785
tf.Tensor(0.08769561, shape=(), dtype=float32)
grads
loss 786
tf.Tensor(0.0876859, shape=(), dtype=float32)
grads
loss 787
tf.Tensor(0.08767617, shape=(), dtype=float32)
grads
loss 788
tf.Tensor(0.08766654, shape=(), dtype=float32)
grads
loss 

grads
loss 823
tf.Tensor(0.087329626, shape=(), dtype=float32)
grads
loss 824
tf.Tensor(0.08732012, shape=(), dtype=float32)
grads
loss 825
tf.Tensor(0.087310486, shape=(), dtype=float32)
grads
loss 826
tf.Tensor(0.08730085, shape=(), dtype=float32)
grads
loss 827
tf.Tensor(0.08729128, shape=(), dtype=float32)
grads
loss 828
tf.Tensor(0.087281734, shape=(), dtype=float32)
grads
loss 829
tf.Tensor(0.08727214, shape=(), dtype=float32)
grads
loss 830
tf.Tensor(0.08726255, shape=(), dtype=float32)
grads
loss 831
tf.Tensor(0.08725302, shape=(), dtype=float32)
grads
loss 832
tf.Tensor(0.08724345, shape=(), dtype=float32)
grads
loss 833
tf.Tensor(0.08723383, shape=(), dtype=float32)
grads
loss 834
tf.Tensor(0.08722427, shape=(), dtype=float32)
grads
loss 835
tf.Tensor(0.08721476, shape=(), dtype=float32)
grads
loss 836
tf.Tensor(0.0872052, shape=(), dtype=float32)
grads
loss 837
tf.Tensor(0.087195575, shape=(), dtype=float32)
grads
loss 838
tf.Tensor(0.08718607, shape=(), dtype=float32)
grads

loss 876
tf.Tensor(0.08682433, shape=(), dtype=float32)
grads
loss 877
tf.Tensor(0.086814776, shape=(), dtype=float32)
grads
loss 878
tf.Tensor(0.08680537, shape=(), dtype=float32)
grads
loss 879
tf.Tensor(0.086795814, shape=(), dtype=float32)
grads
loss 880
tf.Tensor(0.086786345, shape=(), dtype=float32)
grads
loss 881
tf.Tensor(0.0867769, shape=(), dtype=float32)
grads
loss 882
tf.Tensor(0.08676744, shape=(), dtype=float32)
grads
loss 883
tf.Tensor(0.08675801, shape=(), dtype=float32)
grads
loss 884
tf.Tensor(0.08674848, shape=(), dtype=float32)
grads
loss 885
tf.Tensor(0.086738996, shape=(), dtype=float32)
grads
loss 886
tf.Tensor(0.08672957, shape=(), dtype=float32)
grads
loss 887
tf.Tensor(0.08672011, shape=(), dtype=float32)
grads
loss 888
tf.Tensor(0.086710624, shape=(), dtype=float32)
grads
loss 889
tf.Tensor(0.08670115, shape=(), dtype=float32)
grads
loss 890
tf.Tensor(0.08669179, shape=(), dtype=float32)
grads
loss 891
tf.Tensor(0.086682275, shape=(), dtype=float32)
grads
los

grads
loss 926
tf.Tensor(0.0863527, shape=(), dtype=float32)
grads
loss 927
tf.Tensor(0.086343326, shape=(), dtype=float32)
grads
loss 928
tf.Tensor(0.08633392, shape=(), dtype=float32)
grads
loss 929
tf.Tensor(0.08632462, shape=(), dtype=float32)
grads
loss 930
tf.Tensor(0.08631514, shape=(), dtype=float32)
grads
loss 931
tf.Tensor(0.086305805, shape=(), dtype=float32)
grads
loss 932
tf.Tensor(0.08629644, shape=(), dtype=float32)
grads
loss 933
tf.Tensor(0.08628711, shape=(), dtype=float32)
grads
loss 934
tf.Tensor(0.08627772, shape=(), dtype=float32)
grads
loss 935
tf.Tensor(0.08626835, shape=(), dtype=float32)
grads
loss 936
tf.Tensor(0.08625903, shape=(), dtype=float32)
grads
loss 937
tf.Tensor(0.08624962, shape=(), dtype=float32)
grads
loss 938
tf.Tensor(0.0862403, shape=(), dtype=float32)
grads
loss 939
tf.Tensor(0.086230904, shape=(), dtype=float32)
grads
loss 940
tf.Tensor(0.08622147, shape=(), dtype=float32)
grads
loss 941
tf.Tensor(0.0862122, shape=(), dtype=float32)
grads
lo

loss 979
tf.Tensor(0.085858196, shape=(), dtype=float32)
grads
loss 980
tf.Tensor(0.08584894, shape=(), dtype=float32)
grads
loss 981
tf.Tensor(0.085839644, shape=(), dtype=float32)
grads
loss 982
tf.Tensor(0.08583033, shape=(), dtype=float32)
grads
loss 983
tf.Tensor(0.085821144, shape=(), dtype=float32)
grads
loss 984
tf.Tensor(0.08581178, shape=(), dtype=float32)
grads
loss 985
tf.Tensor(0.085802525, shape=(), dtype=float32)
grads
loss 986
tf.Tensor(0.08579323, shape=(), dtype=float32)
grads
loss 987
tf.Tensor(0.085784, shape=(), dtype=float32)
grads
loss 988
tf.Tensor(0.08577473, shape=(), dtype=float32)
grads
loss 989
tf.Tensor(0.08576554, shape=(), dtype=float32)
grads
loss 990
tf.Tensor(0.085756265, shape=(), dtype=float32)
grads
loss 991
tf.Tensor(0.08574697, shape=(), dtype=float32)
grads
loss 992
tf.Tensor(0.08573766, shape=(), dtype=float32)
grads
loss 993
tf.Tensor(0.085728504, shape=(), dtype=float32)
grads
loss 994
tf.Tensor(0.08571923, shape=(), dtype=float32)
grads
loss

loss 1028
tf.Tensor(0.08540581, shape=(), dtype=float32)
grads
loss 1029
tf.Tensor(0.085396685, shape=(), dtype=float32)
grads
loss 1030
tf.Tensor(0.08538745, shape=(), dtype=float32)
grads
loss 1031
tf.Tensor(0.08537827, shape=(), dtype=float32)
grads
loss 1032
tf.Tensor(0.0853691, shape=(), dtype=float32)
grads
loss 1033
tf.Tensor(0.085360005, shape=(), dtype=float32)
grads
loss 1034
tf.Tensor(0.08535074, shape=(), dtype=float32)
grads
loss 1035
tf.Tensor(0.08534155, shape=(), dtype=float32)
grads
loss 1036
tf.Tensor(0.08533239, shape=(), dtype=float32)
grads
loss 1037
tf.Tensor(0.085323215, shape=(), dtype=float32)
grads
loss 1038
tf.Tensor(0.085314095, shape=(), dtype=float32)
grads
loss 1039
tf.Tensor(0.085304946, shape=(), dtype=float32)
grads
loss 1040
tf.Tensor(0.085295774, shape=(), dtype=float32)
grads
loss 1041
tf.Tensor(0.08528665, shape=(), dtype=float32)
grads
loss 1042
tf.Tensor(0.08527745, shape=(), dtype=float32)
grads
loss 1043
tf.Tensor(0.085268244, shape=(), dtype=f

loss 1081
tf.Tensor(0.084921755, shape=(), dtype=float32)
grads
loss 1082
tf.Tensor(0.08491264, shape=(), dtype=float32)
grads
loss 1083
tf.Tensor(0.08490354, shape=(), dtype=float32)
grads
loss 1084
tf.Tensor(0.08489445, shape=(), dtype=float32)
grads
loss 1085
tf.Tensor(0.08488548, shape=(), dtype=float32)
grads
loss 1086
tf.Tensor(0.08487642, shape=(), dtype=float32)
grads
loss 1087
tf.Tensor(0.08486728, shape=(), dtype=float32)
grads
loss 1088
tf.Tensor(0.08485819, shape=(), dtype=float32)
grads
loss 1089
tf.Tensor(0.08484915, shape=(), dtype=float32)
grads
loss 1090
tf.Tensor(0.08484009, shape=(), dtype=float32)
grads
loss 1091
tf.Tensor(0.08483106, shape=(), dtype=float32)
grads
loss 1092
tf.Tensor(0.084821984, shape=(), dtype=float32)
grads
loss 1093
tf.Tensor(0.08481291, shape=(), dtype=float32)
grads
loss 1094
tf.Tensor(0.08480385, shape=(), dtype=float32)
grads
loss 1095
tf.Tensor(0.08479473, shape=(), dtype=float32)
grads
loss 1096
tf.Tensor(0.08478567, shape=(), dtype=float

loss 1130
tf.Tensor(0.08447882, shape=(), dtype=float32)
grads
loss 1131
tf.Tensor(0.084469944, shape=(), dtype=float32)
grads
loss 1132
tf.Tensor(0.08446096, shape=(), dtype=float32)
grads
loss 1133
tf.Tensor(0.08445195, shape=(), dtype=float32)
grads
loss 1134
tf.Tensor(0.0844429, shape=(), dtype=float32)
grads
loss 1135
tf.Tensor(0.08443394, shape=(), dtype=float32)
grads
loss 1136
tf.Tensor(0.084424965, shape=(), dtype=float32)
grads
loss 1137
tf.Tensor(0.08441599, shape=(), dtype=float32)
grads
loss 1138
tf.Tensor(0.08440695, shape=(), dtype=float32)
grads
loss 1139
tf.Tensor(0.084397994, shape=(), dtype=float32)
grads
loss 1140
tf.Tensor(0.08438913, shape=(), dtype=float32)
grads
loss 1141
tf.Tensor(0.08438003, shape=(), dtype=float32)
grads
loss 1142
tf.Tensor(0.08437114, shape=(), dtype=float32)
grads
loss 1143
tf.Tensor(0.08436209, shape=(), dtype=float32)
grads
loss 1144
tf.Tensor(0.08435315, shape=(), dtype=float32)
grads
loss 1145
tf.Tensor(0.08434423, shape=(), dtype=float

loss 1183
tf.Tensor(0.084004834, shape=(), dtype=float32)
grads
loss 1184
tf.Tensor(0.083996, shape=(), dtype=float32)
grads
loss 1185
tf.Tensor(0.08398706, shape=(), dtype=float32)
grads
loss 1186
tf.Tensor(0.083978206, shape=(), dtype=float32)
grads
loss 1187
tf.Tensor(0.08396934, shape=(), dtype=float32)
grads
loss 1188
tf.Tensor(0.08396043, shape=(), dtype=float32)
grads
loss 1189
tf.Tensor(0.08395158, shape=(), dtype=float32)
grads
loss 1190
tf.Tensor(0.08394274, shape=(), dtype=float32)
grads
loss 1191
tf.Tensor(0.08393376, shape=(), dtype=float32)
grads
loss 1192
tf.Tensor(0.083924904, shape=(), dtype=float32)
grads
loss 1193
tf.Tensor(0.08391607, shape=(), dtype=float32)
grads
loss 1194
tf.Tensor(0.08390714, shape=(), dtype=float32)
grads
loss 1195
tf.Tensor(0.08389823, shape=(), dtype=float32)
grads
loss 1196
tf.Tensor(0.08388944, shape=(), dtype=float32)
grads
loss 1197
tf.Tensor(0.083880655, shape=(), dtype=float32)
grads
loss 1198
tf.Tensor(0.08387168, shape=(), dtype=float

loss 1232
tf.Tensor(0.08357124, shape=(), dtype=float32)
grads
loss 1233
tf.Tensor(0.08356243, shape=(), dtype=float32)
grads
loss 1234
tf.Tensor(0.08355366, shape=(), dtype=float32)
grads
loss 1235
tf.Tensor(0.083544895, shape=(), dtype=float32)
grads
loss 1236
tf.Tensor(0.08353601, shape=(), dtype=float32)
grads
loss 1237
tf.Tensor(0.08352725, shape=(), dtype=float32)
grads
loss 1238
tf.Tensor(0.08351846, shape=(), dtype=float32)
grads
loss 1239
tf.Tensor(0.08350958, shape=(), dtype=float32)
grads
loss 1240
tf.Tensor(0.08350085, shape=(), dtype=float32)
grads
loss 1241
tf.Tensor(0.083492085, shape=(), dtype=float32)
grads
loss 1242
tf.Tensor(0.08348328, shape=(), dtype=float32)
grads
loss 1243
tf.Tensor(0.083474524, shape=(), dtype=float32)
grads
loss 1244
tf.Tensor(0.08346568, shape=(), dtype=float32)
grads
loss 1245
tf.Tensor(0.08345686, shape=(), dtype=float32)
grads
loss 1246
tf.Tensor(0.0834482, shape=(), dtype=float32)
grads
loss 1247
tf.Tensor(0.08343935, shape=(), dtype=float

loss 1285
tf.Tensor(0.08310708, shape=(), dtype=float32)
grads
loss 1286
tf.Tensor(0.08309841, shape=(), dtype=float32)
grads
loss 1287
tf.Tensor(0.08308965, shape=(), dtype=float32)
grads
loss 1288
tf.Tensor(0.08308093, shape=(), dtype=float32)
grads
loss 1289
tf.Tensor(0.083072186, shape=(), dtype=float32)
grads
loss 1290
tf.Tensor(0.08306349, shape=(), dtype=float32)
grads
loss 1291
tf.Tensor(0.083054915, shape=(), dtype=float32)
grads
loss 1292
tf.Tensor(0.08304609, shape=(), dtype=float32)
grads
loss 1293
tf.Tensor(0.08303743, shape=(), dtype=float32)
grads
loss 1294
tf.Tensor(0.08302879, shape=(), dtype=float32)
grads
loss 1295
tf.Tensor(0.08301996, shape=(), dtype=float32)
grads
loss 1296
tf.Tensor(0.08301136, shape=(), dtype=float32)
grads
loss 1297
tf.Tensor(0.08300261, shape=(), dtype=float32)
grads
loss 1298
tf.Tensor(0.082993984, shape=(), dtype=float32)
grads
loss 1299
tf.Tensor(0.082985245, shape=(), dtype=float32)
grads
loss 1300
tf.Tensor(0.082976654, shape=(), dtype=fl

loss 1334
tf.Tensor(0.08268228, shape=(), dtype=float32)
grads
loss 1335
tf.Tensor(0.082673736, shape=(), dtype=float32)
grads
loss 1336
tf.Tensor(0.082665175, shape=(), dtype=float32)
grads
loss 1337
tf.Tensor(0.08265641, shape=(), dtype=float32)
grads
loss 1338
tf.Tensor(0.082647786, shape=(), dtype=float32)
grads
loss 1339
tf.Tensor(0.08263922, shape=(), dtype=float32)
grads
loss 1340
tf.Tensor(0.08263057, shape=(), dtype=float32)
grads
loss 1341
tf.Tensor(0.08262194, shape=(), dtype=float32)
grads
loss 1342
tf.Tensor(0.08261332, shape=(), dtype=float32)
grads
loss 1343
tf.Tensor(0.08260478, shape=(), dtype=float32)
grads
loss 1344
tf.Tensor(0.08259615, shape=(), dtype=float32)
grads
loss 1345
tf.Tensor(0.08258754, shape=(), dtype=float32)
grads
loss 1346
tf.Tensor(0.08257893, shape=(), dtype=float32)
grads
loss 1347
tf.Tensor(0.082570344, shape=(), dtype=float32)
grads
loss 1348
tf.Tensor(0.082561664, shape=(), dtype=float32)
grads
loss 1349
tf.Tensor(0.082553074, shape=(), dtype=f

loss 1387
tf.Tensor(0.08222756, shape=(), dtype=float32)
grads
loss 1388
tf.Tensor(0.082219094, shape=(), dtype=float32)
grads
loss 1389
tf.Tensor(0.08221057, shape=(), dtype=float32)
grads
loss 1390
tf.Tensor(0.08220198, shape=(), dtype=float32)
grads
loss 1391
tf.Tensor(0.08219358, shape=(), dtype=float32)
grads
loss 1392
tf.Tensor(0.082184955, shape=(), dtype=float32)
grads
loss 1393
tf.Tensor(0.08217648, shape=(), dtype=float32)
grads
loss 1394
tf.Tensor(0.08216789, shape=(), dtype=float32)
grads
loss 1395
tf.Tensor(0.08215935, shape=(), dtype=float32)
grads
loss 1396
tf.Tensor(0.08215093, shape=(), dtype=float32)
grads
loss 1397
tf.Tensor(0.08214234, shape=(), dtype=float32)
grads
loss 1398
tf.Tensor(0.082133844, shape=(), dtype=float32)
grads
loss 1399
tf.Tensor(0.08212538, shape=(), dtype=float32)
grads
loss 1400
tf.Tensor(0.082116805, shape=(), dtype=float32)
grads
loss 1401
tf.Tensor(0.08210835, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32,

loss 1436
tf.Tensor(0.08181153, shape=(), dtype=float32)
grads
loss 1437
tf.Tensor(0.08180308, shape=(), dtype=float32)
grads
loss 1438
tf.Tensor(0.08179462, shape=(), dtype=float32)
grads
loss 1439
tf.Tensor(0.08178619, shape=(), dtype=float32)
grads
loss 1440
tf.Tensor(0.08177774, shape=(), dtype=float32)
grads
loss 1441
tf.Tensor(0.08176921, shape=(), dtype=float32)
grads
loss 1442
tf.Tensor(0.081760824, shape=(), dtype=float32)
grads
loss 1443
tf.Tensor(0.081752434, shape=(), dtype=float32)
grads
loss 1444
tf.Tensor(0.08174402, shape=(), dtype=float32)
grads
loss 1445
tf.Tensor(0.08173554, shape=(), dtype=float32)
grads
loss 1446
tf.Tensor(0.08172715, shape=(), dtype=float32)
grads
loss 1447
tf.Tensor(0.08171867, shape=(), dtype=float32)
grads
loss 1448
tf.Tensor(0.081710175, shape=(), dtype=float32)
grads
loss 1449
tf.Tensor(0.081701756, shape=(), dtype=float32)
grads
loss 1450
tf.Tensor(0.08169343, shape=(), dtype=float32)
grads
loss 1451
tf.Tensor(0.08168498, shape=(), dtype=flo

loss 1489
tf.Tensor(0.08136605, shape=(), dtype=float32)
grads
loss 1490
tf.Tensor(0.08135766, shape=(), dtype=float32)
grads
loss 1491
tf.Tensor(0.08134936, shape=(), dtype=float32)
grads
loss 1492
tf.Tensor(0.081340924, shape=(), dtype=float32)
grads
loss 1493
tf.Tensor(0.08133261, shape=(), dtype=float32)
grads
loss 1494
tf.Tensor(0.08132428, shape=(), dtype=float32)
grads
loss 1495
tf.Tensor(0.08131596, shape=(), dtype=float32)
grads
loss 1496
tf.Tensor(0.081307516, shape=(), dtype=float32)
grads
loss 1497
tf.Tensor(0.081299156, shape=(), dtype=float32)
grads
loss 1498
tf.Tensor(0.081290916, shape=(), dtype=float32)
grads
loss 1499
tf.Tensor(0.081282526, shape=(), dtype=float32)
grads
loss 1500
tf.Tensor(0.08127413, shape=(), dtype=float32)
grads
loss 1501
tf.Tensor(0.08126579, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-6.9305816 ,  0.05951783,  7.959283  ],
       [-1.4886377 , -0.53309923,  3.0057678 ],
       [ 6.7673287 , 

loss 1538
tf.Tensor(0.08095844, shape=(), dtype=float32)
grads
loss 1539
tf.Tensor(0.08095007, shape=(), dtype=float32)
grads
loss 1540
tf.Tensor(0.08094171, shape=(), dtype=float32)
grads
loss 1541
tf.Tensor(0.08093351, shape=(), dtype=float32)
grads
loss 1542
tf.Tensor(0.08092518, shape=(), dtype=float32)
grads
loss 1543
tf.Tensor(0.08091691, shape=(), dtype=float32)
grads
loss 1544
tf.Tensor(0.08090864, shape=(), dtype=float32)
grads
loss 1545
tf.Tensor(0.08090043, shape=(), dtype=float32)
grads
loss 1546
tf.Tensor(0.08089217, shape=(), dtype=float32)
grads
loss 1547
tf.Tensor(0.08088392, shape=(), dtype=float32)
grads
loss 1548
tf.Tensor(0.08087552, shape=(), dtype=float32)
grads
loss 1549
tf.Tensor(0.080867365, shape=(), dtype=float32)
grads
loss 1550
tf.Tensor(0.08085911, shape=(), dtype=float32)
grads
loss 1551
tf.Tensor(0.08085081, shape=(), dtype=float32)
grads
loss 1552
tf.Tensor(0.080842525, shape=(), dtype=float32)
grads
loss 1553
tf.Tensor(0.08083442, shape=(), dtype=float

loss 1591
tf.Tensor(0.08052178, shape=(), dtype=float32)
grads
loss 1592
tf.Tensor(0.08051358, shape=(), dtype=float32)
grads
loss 1593
tf.Tensor(0.080505386, shape=(), dtype=float32)
grads
loss 1594
tf.Tensor(0.080497265, shape=(), dtype=float32)
grads
loss 1595
tf.Tensor(0.08048907, shape=(), dtype=float32)
grads
loss 1596
tf.Tensor(0.08048085, shape=(), dtype=float32)
grads
loss 1597
tf.Tensor(0.08047268, shape=(), dtype=float32)
grads
loss 1598
tf.Tensor(0.080464445, shape=(), dtype=float32)
grads
loss 1599
tf.Tensor(0.08045631, shape=(), dtype=float32)
grads
loss 1600
tf.Tensor(0.080448054, shape=(), dtype=float32)
grads
loss 1601
tf.Tensor(0.08043985, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-6.9720325 ,  0.05084072,  8.009408  ],
       [-1.5027733 , -0.5407241 ,  3.0275276 ],
       [ 6.806161  , -0.9571231 , -4.2603526 ],
       [-2.2015326 ,  3.157257  , -0.8792204 ]], dtype=float32)>
미분값: 
[<tf.Tensor: shape=(4, 3), dt

loss 1640
tf.Tensor(0.08012225, shape=(), dtype=float32)
grads
loss 1641
tf.Tensor(0.080114126, shape=(), dtype=float32)
grads
loss 1642
tf.Tensor(0.08010601, shape=(), dtype=float32)
grads
loss 1643
tf.Tensor(0.08009784, shape=(), dtype=float32)
grads
loss 1644
tf.Tensor(0.08008981, shape=(), dtype=float32)
grads
loss 1645
tf.Tensor(0.08008165, shape=(), dtype=float32)
grads
loss 1646
tf.Tensor(0.08007353, shape=(), dtype=float32)
grads
loss 1647
tf.Tensor(0.08006546, shape=(), dtype=float32)
grads
loss 1648
tf.Tensor(0.08005741, shape=(), dtype=float32)
grads
loss 1649
tf.Tensor(0.08004925, shape=(), dtype=float32)
grads
loss 1650
tf.Tensor(0.080041185, shape=(), dtype=float32)
grads
loss 1651
tf.Tensor(0.08003304, shape=(), dtype=float32)
grads
loss 1652
tf.Tensor(0.080024935, shape=(), dtype=float32)
grads
loss 1653
tf.Tensor(0.080016896, shape=(), dtype=float32)
grads
loss 1654
tf.Tensor(0.08000882, shape=(), dtype=float32)
grads
loss 1655
tf.Tensor(0.08000068, shape=(), dtype=flo

loss 1693
tf.Tensor(0.07969433, shape=(), dtype=float32)
grads
loss 1694
tf.Tensor(0.079686314, shape=(), dtype=float32)
grads
loss 1695
tf.Tensor(0.07967825, shape=(), dtype=float32)
grads
loss 1696
tf.Tensor(0.079670325, shape=(), dtype=float32)
grads
loss 1697
tf.Tensor(0.07966231, shape=(), dtype=float32)
grads
loss 1698
tf.Tensor(0.07965418, shape=(), dtype=float32)
grads
loss 1699
tf.Tensor(0.07964623, shape=(), dtype=float32)
grads
loss 1700
tf.Tensor(0.07963818, shape=(), dtype=float32)
grads
loss 1701
tf.Tensor(0.07963009, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-7.013066  ,  0.04224173,  8.059036  ],
       [-1.5167722 , -0.5482742 ,  3.049076  ],
       [ 6.8446207 , -0.96356386, -4.29237   ],
       [-2.2128685 ,  3.1774404 , -0.8880653 ]], dtype=float32)>
미분값: 
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.00408268,  0.00085569, -0.00493842],
       [ 0.00139378,  0.00075045, -0.00214425],
       [-0.0

loss 1742
tf.Tensor(0.079302706, shape=(), dtype=float32)
grads
loss 1743
tf.Tensor(0.07929475, shape=(), dtype=float32)
grads
loss 1744
tf.Tensor(0.07928682, shape=(), dtype=float32)
grads
loss 1745
tf.Tensor(0.07927879, shape=(), dtype=float32)
grads
loss 1746
tf.Tensor(0.0792709, shape=(), dtype=float32)
grads
loss 1747
tf.Tensor(0.07926293, shape=(), dtype=float32)
grads
loss 1748
tf.Tensor(0.07925498, shape=(), dtype=float32)
grads
loss 1749
tf.Tensor(0.07924706, shape=(), dtype=float32)
grads
loss 1750
tf.Tensor(0.07923911, shape=(), dtype=float32)
grads
loss 1751
tf.Tensor(0.07923108, shape=(), dtype=float32)
grads
loss 1752
tf.Tensor(0.079223275, shape=(), dtype=float32)
grads
loss 1753
tf.Tensor(0.07921527, shape=(), dtype=float32)
grads
loss 1754
tf.Tensor(0.07920736, shape=(), dtype=float32)
grads
loss 1755
tf.Tensor(0.07919941, shape=(), dtype=float32)
grads
loss 1756
tf.Tensor(0.07919144, shape=(), dtype=float32)
grads
loss 1757
tf.Tensor(0.07918356, shape=(), dtype=float3

loss 1795
tf.Tensor(0.07888332, shape=(), dtype=float32)
grads
loss 1796
tf.Tensor(0.07887547, shape=(), dtype=float32)
grads
loss 1797
tf.Tensor(0.07886745, shape=(), dtype=float32)
grads
loss 1798
tf.Tensor(0.0788597, shape=(), dtype=float32)
grads
loss 1799
tf.Tensor(0.07885182, shape=(), dtype=float32)
grads
loss 1800
tf.Tensor(0.07884393, shape=(), dtype=float32)
grads
loss 1801
tf.Tensor(0.07883604, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-7.0536904 ,  0.03372071,  8.108177  ],
       [-1.5306357 , -0.5557517 ,  3.0704167 ],
       [ 6.8827124 , -0.96994627, -4.324079  ],
       [-2.2241018 ,  3.197432  , -0.8968225 ]], dtype=float32)>
미분값: 
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.00404202,  0.00084821, -0.0048902 ],
       [ 0.00137943,  0.00074428, -0.00212367],
       [-0.00379144,  0.00063557,  0.00315596],
       [ 0.00111812, -0.00198947,  0.00087145]], dtype=float32)>, None]
Loss at epoch 1800: 0

loss 1844
tf.Tensor(0.07849923, shape=(), dtype=float32)
grads
loss 1845
tf.Tensor(0.07849148, shape=(), dtype=float32)
grads
loss 1846
tf.Tensor(0.07848367, shape=(), dtype=float32)
grads
loss 1847
tf.Tensor(0.07847589, shape=(), dtype=float32)
grads
loss 1848
tf.Tensor(0.07846803, shape=(), dtype=float32)
grads
loss 1849
tf.Tensor(0.07846029, shape=(), dtype=float32)
grads
loss 1850
tf.Tensor(0.078452446, shape=(), dtype=float32)
grads
loss 1851
tf.Tensor(0.078444704, shape=(), dtype=float32)
grads
loss 1852
tf.Tensor(0.078436896, shape=(), dtype=float32)
grads
loss 1853
tf.Tensor(0.07842916, shape=(), dtype=float32)
grads
loss 1854
tf.Tensor(0.078421295, shape=(), dtype=float32)
grads
loss 1855
tf.Tensor(0.078413606, shape=(), dtype=float32)
grads
loss 1856
tf.Tensor(0.078405805, shape=(), dtype=float32)
grads
loss 1857
tf.Tensor(0.07839794, shape=(), dtype=float32)
grads
loss 1858
tf.Tensor(0.078390196, shape=(), dtype=float32)
grads
loss 1859
tf.Tensor(0.07838248, shape=(), dtype=

loss 1897
tf.Tensor(0.078087956, shape=(), dtype=float32)
grads
loss 1898
tf.Tensor(0.07808031, shape=(), dtype=float32)
grads
loss 1899
tf.Tensor(0.07807253, shape=(), dtype=float32)
grads
loss 1900
tf.Tensor(0.078064844, shape=(), dtype=float32)
grads
loss 1901
tf.Tensor(0.07805711, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-7.0939145 ,  0.0252765 ,  8.156841  ],
       [-1.5443672 , -0.56315696,  3.0915534 ],
       [ 6.920446  , -0.9762717 , -4.3554883 ],
       [-2.2352362 ,  3.2172344 , -0.9054936 ]], dtype=float32)>
미분값: 
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.00400248,  0.00084092, -0.00484337],
       [ 0.00136689,  0.0007369 , -0.00210365],
       [-0.00375516,  0.00062991,  0.00312537],
       [ 0.00110881, -0.00197098,  0.00086229]], dtype=float32)>, None]
Loss at epoch 1900: 0.078049
loss 1902
tf.Tensor(0.078049436, shape=(), dtype=float32)
grads
loss 1903
tf.Tensor(0.07804166, shape=(), dtype=flo

loss 1946
tf.Tensor(0.07771145, shape=(), dtype=float32)
grads
loss 1947
tf.Tensor(0.07770379, shape=(), dtype=float32)
grads
loss 1948
tf.Tensor(0.0776961, shape=(), dtype=float32)
grads
loss 1949
tf.Tensor(0.07768847, shape=(), dtype=float32)
grads
loss 1950
tf.Tensor(0.07768078, shape=(), dtype=float32)
grads
loss 1951
tf.Tensor(0.07767317, shape=(), dtype=float32)
grads
loss 1952
tf.Tensor(0.07766561, shape=(), dtype=float32)
grads
loss 1953
tf.Tensor(0.0776579, shape=(), dtype=float32)
grads
loss 1954
tf.Tensor(0.07765032, shape=(), dtype=float32)
grads
loss 1955
tf.Tensor(0.077642635, shape=(), dtype=float32)
grads
loss 1956
tf.Tensor(0.07763499, shape=(), dtype=float32)
grads
loss 1957
tf.Tensor(0.07762745, shape=(), dtype=float32)
grads
loss 1958
tf.Tensor(0.07761976, shape=(), dtype=float32)
grads
loss 1959
tf.Tensor(0.07761223, shape=(), dtype=float32)
grads
loss 1960
tf.Tensor(0.07760456, shape=(), dtype=float32)
grads
loss 1961
tf.Tensor(0.07759689, shape=(), dtype=float32)

loss 1999
tf.Tensor(0.0773081, shape=(), dtype=float32)
grads
loss 2000
tf.Tensor(0.07730058, shape=(), dtype=float32)
grads
loss 2001
tf.Tensor(0.07729298, shape=(), dtype=float32)
grads
<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-7.133745  ,  0.0169077 ,  8.205035  ],
       [-1.5579683 , -0.57049257,  3.11249   ],
       [ 6.957826  , -0.9825417 , -4.386596  ],
       [-2.2462711 ,  3.2368548 , -0.9140792 ]], dtype=float32)>
미분값: 
[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.00396352,  0.00083302, -0.00479656],
       [ 0.00135362,  0.00072993, -0.00208364],
       [-0.00372064,  0.00062408,  0.00309647],
       [ 0.00109848, -0.001953  ,  0.00085444]], dtype=float32)>, None]
Loss at epoch 2000: 0.077285


Prediction Check

In [12]:
sample_data = [[2,1,3,2]]
sample_data = np.asarray(sample_data, dtype = np.float32)

a = hypothesis(sample_data)
# 여기서 가장 높은 예측값을 a로 지정함 
print(a)
print(tf.argmax(a,1))
    # 가장 높은 예측값이 가리키는 값을 뽑는 것 0,1,2 중 2를 뽑음

tf.Tensor([[0.00112886 0.08154673 0.9173244 ]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [13]:
# 실제 데이터 가지고 해보자
b = hypothesis(x_data)
print(b)
print(tf.argmax(b,1))
    # 결과를 보면 첫번째에서 가장 높은 값 2, 두번째에서 가장 높은 값 2 ... 마지막에서 가장 높은 값 0
    # 이런 식으로 결과가 나오게 됨.
print(tf.argmax(y_data, 1))
    # y랑 비교해보면 같으므로 학습이 정상적으로 되었음을 알 수 있음

tf.Tensor(
[[2.1975952e-06 1.2331170e-03 9.9876475e-01]
 [1.1288594e-03 8.1546687e-02 9.1732442e-01]
 [2.2205539e-07 1.6418624e-01 8.3581358e-01]
 [6.3921816e-06 8.5045439e-01 1.4953922e-01]
 [2.6150808e-01 7.2644734e-01 1.2044534e-02]
 [1.3783246e-01 8.6214006e-01 2.7417480e-05]
 [7.4242145e-01 2.5754160e-01 3.6978410e-05]
 [9.2197549e-01 7.8023903e-02 6.0005692e-07]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


Convert as Class

In [14]:
class softmax_classifer(tf.keras.Model):
    def __init__(self, nb_classes):
        super(softmax_classifer, self).__init__()
        self.W = tf.Variable(tf.random.normal((4, nb_classes)), name = 'weight')
        self.b = tf.Variable(tf.random.normal((nb_classes,)), name = 'bias')
        
    def softmax_regression(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)
    
    def cost_fn(self, X, Y):
        logits = self.softmax_regression(X)
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(logits), axis = 1))
        
    def grad_fn(self, X, Y):
        with tf.GradientTape() as tape:
            cost = self.cost_fn(x_data, y_data)
            grads = tape.gradient(cost, self.variables)
            return grads
        
    def fit(self, X, Y, epochs = 2000, verbose = 500):
        optimizer = tf.keras.optimizers.SGD(learning_rate = 0.1)
        
        for i in range(epochs):
            grads = self.grad_fn(X, Y)
            optimizer.apply_gradients(zip(grads, self.varialbes))
            if((i == 0)|((i + 1) % verbose == 0)):
               print('Loss at epochs %d: %f' %(i+1, self.cost_fn(X, Y).numpy()))
            
model = softmax_classifer(nb_classes)
model.fit(x_data, y_data)

TypeError: Cannot convert value None to a TensorFlow DType.